name: publish cli artifacts
on:
  push:
    branches:
      - main
    paths:
      - "Mir.Ethernity.Dat.Cli/**/*"
      - .github/workflows/cli.yml
jobs:
  publish-cli:
    name: publish-cli
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - run: dotnet publish Mir.Ethernity.Dat.Cli -c release -r win-x64
    - name: Upload artifact CLI - Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dat-encoder
        path: Mir.Ethernity.Dat.Cli/bin/release/net6.0-windows/win-x64/publish
  publish-ui:
    name: publish-ui
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - run: dotnet publish Mir.Ethernity.Dat.Editor -c release -r win-x64
    - name: Upload artifact Editor - Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dat-encoder
        path: Mir.Ethernity.Dat.Editor/bin/release/net6.0-windows/win-x64/publish