name: publish cli artifacts
on:
  push:
    branches:
      - main
    paths:
      - "Mir.Ethernity.Dat.Cli/**/*"
      - .github/workflows/cli.yml
jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - run: dotnet publish Mir.Ethernity.Dat.Cli -c release -r win-x64
    - name: Upload artifact - Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: dat-encoder
        path: Mir.Ethernity.Dat.Cli/bin/release/netcoreapp3.1/win-x64/publish/**/*