name: publish to nuget
on:
  push:
    branches:
      - main
    paths:
      - "Mir.Ethernity.Dat/**/*"
      - ".github/workflows/publish.yml"
jobs:
  publish:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Mir.Ethernity.Dat/Mir.Ethernity.Dat.csproj
          PACKAGE_NAME: Mir.Ethernity.Dat
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org